export const LOLLAPALOOZA_ARGENTINA_2025 = [
  'Olivia Rodrigo',
  'Justin Timberlake',
  'Shawn Mendes',
  'Alanis Morissette',
  'Tool',
  'Rüfüs Du Sol',
  'Tan Biónica',
  'Benson Boone',
  'Foster The People',
  'Tate McRae',
  'Wos',
  'Nathy Peluso',
  'Parcels',
  'Teddy Swims',
  'Girl in Red',
  'James Hype',
  'Los Ángeles Azules',
  'Zedd',
  'Mon Laferte',
  'Charlotte De Witte',
  'Artemas',
  'The Marías',
  'Rawayana',
  'Fontaines D.C.',
  'Sepultura',
  'Inhaler',
  'Caribou',
  'JPEGMAFIA',
  'Wave to Earth',
  'BLOND:ISH',
  'Lasso',
  'Barry Can’t Swim',
  'Michael Kiwanuka',
  'San Holo',
  'Ana Mena',
  'Disco Lines',
  'Kasablanca',
  'Nessa Barret',
  'Marina Reche',
  'Elena Rose',
];
