export const LOLLAPALOOZA_ARGENTINA_2025 = [
  'Olivia Rodrigo',
  'Justin Timberlake',
  'Shawn Mendes',
  'Alanis Morissette',
  'Tool',
  'Rüfüs Du Sol',
  'Tan Biónica',
  'Benson Boone',
  'Foster The People',
  'Tate McRae',
  'Wos',
  'Nathy Peluso',
  'Parcels',
  'Teddy Swims',
  'Girl in Red',
  'James Hype',
  'Los Ángeles Azules',
  'Zedd',
  'Mon Laferte',
  'Charlotte De Witte',
  'Artemas',
  'The Marías',
  'Rawayana',
  'Fontaines D.C.',
  'Sepultura',
  'Inhaler',
  'Caribou',
  'JPEGMAFIA',
  'Wave to Earth',
  'BLOND:ISH',
  'Lasso',
  'Barry Can’t Swim',
  'Michael Kiwanuka',
  'San Holo',
  'Ana Mena',
  'Disco Lines',
  'Kasablanca',
  'Nessa Barret',
  'Marina Reche',
  'Elena Rose',
];

export const SHORT_LOLLAPALOOZA_ARGENTINA_2025 = [
  'Olivia Rodrigo',
  'Justin Timberlake',
  'Shawn Mendes',
  'Alanis Morissette',
  // 'Tool',
  // 'Rüfüs Du Sol',
  'Tan Biónica',
  'Benson Boone',
  'Foster The People',
  'Tate McRae',
  'Wos',
  'Nathy Peluso',
  // 'Parcels',
  'Teddy Swims',
  'Girl in Red',
  // 'James Hype',
  // 'Los Ángeles Azules',
  // 'Zedd',
  // 'Mon Laferte',
  // 'Charlotte De Witte',
  // 'Artemas',
  // 'The Marías',
  // 'Rawayana',
  // 'Fontaines D.C.',
  // 'Sepultura',
  // 'Inhaler',
  // 'Caribou',
  // 'JPEGMAFIA',
  // 'Wave to Earth',
  // 'BLOND:ISH',
  // 'Lasso',
  // 'Barry Can’t Swim',
  // 'Michael Kiwanuka',
  // 'San Holo',
  // 'Ana Mena',
  // 'Disco Lines',
  // 'Kasablanca',
  // 'Nessa Barret',
  // 'Marina Reche',
  // 'Elena Rose',
];

export const FRIDAY_LOLLAPALOOZA_ARGENTINA_2025 = [
  'Justin Timberlake',
  'Alanis Morissette',
  'Foster The People',
  'Los Ángeles Azules',
  'Mon Laferte',
  'Charlotte De Witte',
  'Catriel & Paco Amoroso',
  'Parcels',
  'Blond:ish',
  'Lasso',
  'Barry Can’t Swim',
  'Ana Mena',
  'Pablopablo',
];

export const SATURDAY_LOLLAPALOOZA_ARGENTINA_2025 = [
  'Shawn Mendes',
  'Tool',
  'Wos',
  'Tate McRae',
  `La Konga`,
  'Zedd',
  'Teddy Swims',
  'The Marías',
  'Sepultura',
  'Inhaler',
  'Wave to Earth',
  'San Holo',
  'Artemas',
  'Kasablanca',
  'Elena Rose',
  'Luz Gaggi',
];

export const SUNDAY_LOLLAPALOOZA_ARGENTINA_2025 = [
  'Olivia Rodrigo',
  'Rüfüs Du Sol',
  'Tan Biónica',
  'Nathy Peluso',
  'Benson Boone',
  'Girl in Red',
  'James Hype',
  'Rawayana',
  'Fontaines D.C.',
  'Caribou',
  'JPEGMAFIA',
  'DISCO LINES',
  'LITTLE JESUS',
  'ARON',
];
